spring:
  cloud:
    gateway:
      routes:
        - id: car-finder-extractor
          uri: lb://car-finder-extractor
          predicates:
            - Path=/api/1.0/extractor/**
        - id: car-finder-api
          uri: lb://car-finder-api
          predicates:
            - Path=/api/1.0/carData/**
      