spring:
  application:
    name: api-gateway

server:
  port: 8080
  
eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
