version: '3'
services:
  mongodb:
    image: mongo:6.0.2
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./mongo-data:/data/mongo
      
  activemq:
    image: apache/activemq
    ports:
      - 61616:61616
    volumes:
      - ./activemq/data:/data/activemq
      - ./activemq/log:/var/log/activemq