spring:
  application:
    name: car-finder-api
  profiles:
    active: mongodb

server:
  port: 0

api:
  version: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

